#!/bin/bash

set -euo pipefail

export FROST_SERVER=frost.met.no

STATIONS="SN99710 SN99720 SN99735 SN99740 SN99752 SN99754 SN99760 SN99765 SN99790 SN99840 SN99880 SN99910 SN99927 SN99935 SN99938"
JSON_OUTPUT_DIR=/tmp/
NC_OUTPUT_DIR=.
DURATION=3

while getopts "hj:o:s:d:" opt; do 
    case "$opt" in 
    j)
        JSON_OUTPUT_DIR=$OPTARG
        ;;
    o)
        NC_OUTPUT_DIR=$OPTARG
        ;;
    s)
        STATIONS=$OPTARG
        ;;
    d)
        DURATION=$OPTARG
        ;;
    h)
        echo Usage $0 [-j JSON_OUTPUT_DIR] [-o NC_OUTPUT_DIR] [-s STATIONS]
        exit
    esac
done


if [ -z "$FROST_KEY" ]; then 
    echo "Missing FROST_KEY"
    exit 1
fi

echo download elements list

frost download elements > "$JSON_OUTPUT_DIR/elements.json"

echo start loop

for station in $STATIONS; do
    echo "Extract station $station"
    frost download source -s$station > "$JSON_OUTPUT_DIR/$station.json"
    new_files=$(frost download observations --output="$JSON_OUTPUT_DIR" -s"$station" --duration "$DURATION")

    output_file="$NC_OUTPUT_DIR/$station.nc"
    if [ -f "$output_file" ]; then
        append="--append"
    else
        append=""
    fi

    frost write netcdf \
        -o"$output_file" \
        $append \
        -s"$JSON_OUTPUT_DIR/$station.json" \
        -e"$JSON_OUTPUT_DIR/elements.json" \
        $new_files

    echo "done"
done

